TS.tstring = {
  appTitle: '[!!ŢŚţřįņġ.ĵŜ!!]',
  appSubTitle: '[!!Ěxämƿļĕ ŏƒ ťŗåńśľäŧĕđ ťēxť ŝŧŕįƞğš äŋď ƒơřēĩğń ĺȃňģůãġě śűƥƿőŕŧ!!]',
  blogLink: '[!!Ŗėàđ ŧĥȇ ťĕčħńīċāł ąŗŧįċļę őŉ mɏ ƃĺőġ!!]',
  programListing: '[!!Ƥŗơģŕąm Łıšţĩńğ!!]',
  english: '[!!Ēňġłıŝħ!!]',
  french: '[!!Ƒŕēňĉĥ!!]',
  spanish: '[!!Ŝƿāŉīŝĥ!!]',
  italian: '[!!İţǻĺĩáń!!]',
  german: '[!!Ġȅŕmáń!!]',
  psuedo: '[!!Ƥŝũěđō Łơćâļĩźȅ!!]',
  select: '[!!Şęłĕćţ!!]',
  title: '[!!Ţıŧļȇ!!]',
  date: '[!!Đăţȇ!!]',
  channel: '[!!Čħȃƞņȇľ!!]',
  duration: '[!!Ɖűřȁťīŏŋ!!]',
  synopsis: '[!!Śƴņŏƿśįş!!]',
  selectedProgram: '[!!Ȳőŭ ŝęľėćţĕđ ťĥȅ ƿřơĝŗąm ŧįţłėđ!!]',
  programDate: 'DD/MM/YYYY HH:mm'
};