TS.tstring = {
  appTitle: 'TString.JS',
  appSubTitle: 'Exemple de chaînes de texte traduites en langue étrangère et de soutien',
  blogLink: 'Lire l\'article technique sur mon blog',
  programListing: 'Liste Programme',
  english: 'Anglais',
  french: 'Français',
  spanish: 'Espagnol',
  italian: 'Italien',
  german: 'Allemand',
  psuedo: '[!!Ƥŝũěđō Łơćâļĩźȅ!!]',
  select: 'Sélectionner',
  title: 'Titre',
  date: 'Date',
  channel: 'Canal',
  duration: 'Durée',
  synopsis: 'Synopsis',
  selectedProgram: 'Vous avez sélectionné le programme intitulé',
  programDate: 'DD/MM/YYYY HH:mm'
};